### ISSUE TITLE
object has no attribute 'contribute_to_class' prevent loaddata

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#445]
This is related with https://github.com/radiac/django-tagulous/issues/14.

~~~
$ python manage.py loaddata fixtures/*
Traceback (most recent call last):
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/serializers/python.py", line 99, in Deserializer
    Model = _get_model(d["model"])
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/tagulous/serializers/base.py", line 70, in _get_model
    Model = RealModel._detag_to_serializable()
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/tagulous/models/tagged.py", line 413, in _detag_to_serializable
    clone_field.contribute_to_class(FakeTaggedModel, field.name)
AttributeError: 'ManyToOneRel' object has no attribute 'contribute_to_class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 166, in load_label
    for obj in objects:
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/tagulous/serializers/base.py", line 52, in wrapper
    for obj in obj_generator:
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/serializers/json.py", line 88, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/django/core/serializers/python.py", line 99, in Deserializer
    Model = _get_model(d["model"])
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/tagulous/serializers/base.py", line 70, in _get_model
    Model = RealModel._detag_to_serializable()
  File "/home/raniere/anaconda3/envs/lowfat/lib/python3.6/site-packages/tagulous/models/tagged.py", line 413, in _detag_to_serializable
    clone_field.contribute_to_class(FakeTaggedModel, field.name)
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/raniere/SSI/src/lowfat/fixtures/demo.json': 'ManyToOneRel' object has no attribute 'contribute_to_class'
~~~

**Comment by rgaiacs** [comment]
There are a fix that will be in release django-tagulous 0.13.0.
