### ISSUE TITLE
Cannot load demo fixtures with Django 3.2

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#624]
`python manage.py loaddata fixtures/demo.json`

Works fine on Django 3.1, but not 3.2 due to error below:

```Traceback (most recent call last):
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/serializers/json.py", line 70, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/serializers/python.py", line 148, in Deserializer
    obj = base.build_instance(Model, data, using)
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/serializers/base.py", line 270, in build_instance
    return Model(**data)
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/db/models/base.py", line 413, in __init__
    raise TypeError('Abstract models cannot be instantiated.')
TypeError: Abstract models cannot be instantiated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    for obj in objects:
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/tagulous/serializers/base.py", line 51, in wrapper
    for obj in obj_generator:
  File "/home/jag1e17/projects/lowfat/.venv/lib64/python3.7/site-packages/django/core/serializers/json.py", line 74, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/jag1e17/projects/lowfat/fixtures/demo.json':```

**Comment by jag1g13** [comment]
Models in `demo.json` and whether they can be imported individually:

- [ ] "auth.user"
- [ ] "lowfat.fundactivity"
- [ ] "lowfat.termsandconditions"
- [ ] "lowfat.claimant"
- [ ] "lowfat.fund"
- [ ] "lowfat.expense"
- [ ] "lowfat.blog"
- [ ] "lowfat.generalsentmail"
- [ ] "lowfat.fundsentmail"
- [ ] "lowfat.expensesentmail"
- [ ] "lowfat.blogsentmail"

**Comment by jag1g13** [comment]
We narrowed this down to the model `Fund` which has tags using Tagulous. Using the debugger we were able to check that all fields loaded except `activity` which is the tag field.

Issue submitted at https://github.com/radiac/django-tagulous/issues/127
